<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class EstacionController extends Controller
{
    public function index()
    {
        $estaciones =  [
            [
                "id" => 1,
                "nombre" => "CAUCEL",
                "num_estacion" => '12563',
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
                'coordenadas'=> ["lat"=>21.008713549470595, "lng"=> -89.71594292433007],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 2,
                "nombre" => "CHUBURNA",
                "num_estacion" => '12127',
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 20 POR 25, NO. 111, CHUBURNÁ DE HIDALGO, MÉRIDA, YUCATÁN, C. P. 97205',
                'coordenadas'=> ["lat"=>21.009307738560405, "lng"=> -89.63147082774572],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 3,
                "nombre" => "KANASIN 58",
                "num_estacion" => '12726',
               "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 58, NÚMERO 602, SIN COLONIA, KANASÍN, YUCATÁN, C. P. 97370',
                'coordenadas'=> ["lat"=>20.924756981369864, "lng"=> -89.58132795703577],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 4,
                "nombre" => "MAYA",
                "num_estacion" => '08115',
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'TABLAJE DE TIERRA NÚMERO CATASTRAL 17280, MÉRIDA CENTRO, MÉRIDA, YUCATÁN, C.P. 97300',
                'coordenadas'=> ["lat"=>21.05708091203714, "lng"=> -89.63125457310008],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 5,
                "nombre" => "MOTUL",
                "num_estacion" => '13346',
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 28 NO. 298, CENTRO, C. P. 97430',
                'coordenadas'=> ["lat"=>21.103809181096732, "lng"=> -89.28419181343048],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 6,
                "nombre" => "MULSAY",
                "num_estacion" => '60007',
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 41 POR CALLE 12 DIAGONAL NO. 232, MULSAY, C. P. 97246',
                'coordenadas'=> ["lat"=>20.966955821411553, "lng"=> -89.67216335320917],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => true,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 7,
                "nombre" => "SAN PEDRO",
                "num_estacion" => 11569.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CARRETERA MÉRIDA-VALLADOLID, KM 9.50, TABLAJE CATASTRAL, NO. 16264, SIN COLONIA, KANASÍN, YUCATÁN, C.P. 97370',
                'coordenadas'=> ["lat"=>20.93970220846479, "lng"=> -89.54286582037267],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 8,
                "nombre" => "HECELCHAKAN",
                "num_estacion" => '12766',
                "zona" => 'CAMPECHE',
                "status" => "Activo",
                "direccion" => 'CALLE S/N, ESQUINA CALLE 20, No. 3 FRACCIÓN A, BARRIO DE SAN FRANCISCO, HECELCHAKÁN, CAMPECHE, C.P. 24800',
                'coordenadas'=> ["lat"=>20.170903445859455, "lng"=> -90.14024246104532],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 9,
                "nombre" => "KOPOMÁ",
                "num_estacion" => 11328.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CARRETERA MÉRIDA – CAMPECHE KM 57.00 MARGEN IZQUIERDO (PARCELA NÚMERO 90, FRACCIÓN II), SIN COLONIA, KOPOMÁ, C.P. 97818',
                'coordenadas'=> ["lat"=>20.62069296899633, "lng"=> -89.94669196268441],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 10,
                "nombre" => "MUNA",
                "num_estacion" => 11603.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 31 NO. 245-C, SIN COLONIA, C. P. 97930',
                'coordenadas'=> ["lat"=>20.483014459915147, "lng"=> -89.70391092437399],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 11,
                "nombre" => "PETO",
                "num_estacion" => 13211.0,
               "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 31, NO. 245-C, SIN COLONIA, PETO, YUCATÁN , C.P. 97930	',
                'coordenadas'=> ["lat"=>20.12750640432563, "lng"=> -88.92973552383536],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 12,
                "nombre" => "TENABO",
                "num_estacion" => 12776,
               "zona" => 'CAMPECHE',
                "status" => "Activo",
                "direccion" => 'CALLE 10, ESQUINA CALLE 23, SIN No, SIN COLONIA, TENABO, CAMPECHE, C.P. 24705',
                'coordenadas'=> ["lat"=>20.034515841318036, "lng"=> -90.22683509691403],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 13,
                "nombre" => "TZUCACAB",
                "num_estacion" => 565.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 31, TABLAJE CATASTRAL 1103, SIN COLONIA, TZUCACAB, YUCATÁN, C. P. 97960',
                'coordenadas'=> ["lat"=>20.071570089563476, "lng"=> -89.0439261411371],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 14,
                "nombre" => "UMAN",
                "num_estacion" => 11393.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 16-A POR CALLE S/N, TABLAJE CATASTRAL 14177, SIN COLONIA, UMÁN, YUCATÁN, C. P. 97390',
                'coordenadas'=> ["lat"=>20.905632208051596, "lng"=> -89.72089847293579],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 15,
                "nombre" => "CHEMAX",
                "num_estacion" => 3875.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'TABLAJE CATASTRAL NÚMERO 4069, SIN COLONIA, CHEMAX, YUCATÁN, C.P. 97770',
                'coordenadas'=> ["lat"=>20.65768711914171, "lng"=> -87.94833510883618],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 16,
                "nombre" => "COLONIA YUCATÁN",
                "num_estacion" => '12257',
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CARRETERA TIZIMÍN-COLONIA YUCATÁN KM. 7.68, FRACCIÓN DEL PREDIO RÚSTICO DENOMINADO LA SIERRA NO. 1TABLAJE CATASTRAL 6971, COLONIA YUCATÁN, LOCALIDAD CHAN CENOTE, TIZIMÍN, YUCATÁN, C.P. 97710',
                'coordenadas'=> ["lat"=>21.20503936768233, "lng"=> -87.72367719442869],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
               "is_city" => false,
                "is_beach" => false,
                "is_town" => true,
            ],
            [
                "id" => 17,
                "nombre" => "EL CUYO",
                "num_estacion" => 3941.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'PUERTO DE ABRIGO EL CUYO S/N, CENTRO, TIZIMÍN, YUCATÁN, C. P. 97713',
                'coordenadas'=> ["lat"=>21.51752809106912, "lng"=> -87.68636919278724],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => false,
                "is_beach" => true,
                "is_town" => false,
            ],
            [
                "id" => 18,
                "nombre" => "TIZIMIN",
                "num_estacion" => 11807.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => 'CALLE 49 NO. 192-A, HUAYITA, TIZIMÍN, YUCATÁN, C.P. 97700',
                'coordenadas'=> ["lat"=>21.146659895986392, "lng"=> -88.137379985606],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            [
                "id" => 19,
                "nombre" => "YAXCHE",
                "num_estacion" => 8295.0,
                "zona" => 'YUCATÁN',
                "status" => "Activo",
                "direccion" => '	CALLE 41, TABLAJE CATASTRAL 4088, S/C, VALLADOLID, YUCATÁN, C.P. 97780',
                'coordenadas'=> ["lat"=>20.69353051135462, "lng"=> -88.17324343638975],
                "combustibles" => [
                    "MAGNA" => true,
                    "PREMIUM" => true,
                    "DIESEL" => false,
                ],
                "is_city" => true,
                "is_beach" => false,
                "is_town" => false,
            ],
            // [
            //     "id" => 20,
            //     "nombre" => "EBTÚN",
            //     "num_estacion" => 8192.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 21,
            //     "nombre" => "EXPOFERIA",
            //     "num_estacion" => 11545.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 22,
            //     "nombre" => "PISTE",
            //     "num_estacion" => '559',
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'TABLAJE CATASTRAL NÚMERO 4097, LOCALIDAD PISTÉ, TICUM, YUCATÁN, C.P. 97751',
            //     'coordenadas'=> ["lat"=>20.699401820002947, "lng"=> -88.59913554180915],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 23,
            //     "nombre" => "SACIABIL",
            //     "num_estacion" => '5732',
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'Av. Nichupte, Chun Huas,Valladolid, YucatÁn, c.p 97780',
            //     'coordenadas'=> ["lat"=>20.672251325178415, "lng"=> -88.20471850825659],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 24,
            //     "nombre" => "VALLADOLID MATRIZ",
            //     "num_estacion" => '13004',
            //    "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 41 POR 62, TABLAJE CATASTRAL 4104, BACALAR, VALLADOLID, YUCATÁN, C.P. 97784',
            //     'coordenadas'=> ["lat"=>20.690619350387962, "lng"=> -88.21835315218463],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 25,
            //     "nombre" => "ZACÍ",
            //     "num_estacion" => '4886',
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 42 NO. 142, FRACCIONAMIENTO CAMPESTRE DEL PEDREGAL, VALLADOLID, YUCATÁN, C.P. 97780',
            //     'coordenadas'=> ["lat"=>20.710654173806805, "lng"=> -88.2028200066157],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 26,
            //     "nombre" => "BUENAVISTA",
            //     "num_estacion" => '13103',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'AV. SAN LUCAS, RESTO SECCIÓN 1 DEL LOTE 4 S/C, CARMEN, CAMPECHE, C.P. 24157',
            //     'coordenadas'=> ["lat"=>18.66543098214472, "lng"=> -91.75725073986354],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 27,
            //     "nombre" => "CHAMPOTÓN MALECON",
            //     "num_estacion" => '12777',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 38 (AV. CARLOS SANSORES PÉREZ), ESQUINA CALLE 9, SIN NÚMERO, ISSSTE, CHAMPOTÓN, CAMPECHE, C.P. 24400',
            //     'coordenadas'=> ["lat"=>19.342737306256616, "lng"=> -90.732359964604],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 28,
            //     "nombre" => "CHAMPOTÓN RESTAURANTE",
            //     "num_estacion" => '13117',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 34 ESQUINA CON CALLE 41 No. 89, ULISES SANSORES, CHAMPOTÓN, CAMPECHE, C.P. 24400',
            //     'coordenadas'=> ["lat"=>19.347150361022468, "lng"=> -90.72410381285609],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 29,
            //     "nombre" => "CHAMPOTÓN ECHEVERRÍA",
            //     "num_estacion" => '60029',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'AV. EUGENIO ECHEVERRíA CASTELLOT, COL. LAS BRISAS, C.P. 24400',
            //     'coordenadas'=> ["lat"=>19.334977210780668, "lng"=> -90.72697133606992],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 30,
            //     "nombre" => "COLOSIO",
            //     "num_estacion" => '60012',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'Av. Luis Donaldo Colosio Murrieta 258, Barrio de San José, 24040 San Francisco de Campeche, Campeche.',
            //     'coordenadas'=> ["lat"=>19.83087423889399, "lng"=> -90.5387707466267],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 31,
            //     "nombre" => "ESCARCEGA LEMUS",
            //     "num_estacion" => '12886',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 30 (AV. HÉCTOR PÉREZ MARTÍNEZ), LOTE 3, MORELOS, ESCÁRCEGA, CAMPECHE, C.P. 24350',
            //     'coordenadas'=> ["lat"=>18.605354971016514, "lng"=> -90.73523592266363],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 32,
            //     "nombre" => "ESCARCEGA ALARCÓN",
            //     "num_estacion" => '60009',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'AV. SOLIDARIDAD, S/N, ENTRE CALLES 59 Y 59 B COL. IGNACIO ZARAGOZA, ESCÁRCEGA, CAMPECHE, C.P. 24350',
            //     'coordenadas'=> ["lat"=>18.607947324560033, "lng"=> -90.74810475769057],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 33,
            //     "nombre" => "IMI",
            //     "num_estacion" => '60011',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'AV. PEDRO SAINZ DE BARANDA (O AV. CARRETERA COSTERA DEL GOLFO), No. 118, COL. POBLADO IMI SECCIÓN II, C.P. 24560',
            //     'coordenadas'=> ["lat"=>19.88003574210461, "lng"=> -90.4820469],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 34,
            //     "nombre" => "ISLA AGUADA",
            //     "num_estacion" => '13116',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'CARRETERA FEDERAL CARMEN-CHAMPOTÓN KM 42, FRACCIÓN DEL PREDIO URBANO S/N FRACCIÓN “A”, ISLA AGUADA, C.P. 24327',
            //     'coordenadas'=> ["lat"=>18.808296889964346, "lng"=> -91.47092042509993],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 35,
            //     "nombre" => "JUAREZ",
            //     "num_estacion" => '60004',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'LIC. BENITO JUÁREZ, LOTE 275, HACIENDA REAL CAMPECHE EL FÉNIX, SAN FRANCISCO DE CAMPECHE, C.P. 24023',
            //     'coordenadas'=> ["lat"=>19.863385729618823, "lng"=> -90.4869117730135],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 36,
            //     "nombre" => "PALMIRA",
            //     "num_estacion" => '13191',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'AV. NARDOS, ESQUINA CON AV. PALMERAS, SIN No, FRACCIONAMIENTO PALMIRA, C.P. 24154',
            //     'coordenadas'=> ["lat"=>18.659565076866507, "lng"=> -91.79397044200569],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 37,
            //     "nombre" => "PGJ",
            //     "num_estacion" => '60005',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'AV. JOSÉ LÓPEZ PORTILLO No. 309, ENTRE PRIVADA PROLONGACIÓN PEDRO MORENO Y AVENIDA PATRICIO TRUEBA, SASCALUM, C.P. 24095',
            //     'coordenadas'=> ["lat"=>19.814911823355665, "lng"=> -90.53034718650675],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 38,
            //     "nombre" => "VILLA CABRA",
            //     "num_estacion" => '60006',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 108 POR CALLE VILLACABRA, No. 117 Y 117–A, BELLAVISTA, SAN FRANCISCO DE CAMPECHE, C.P. 24020',
            //     'coordenadas'=> ["lat"=>19.851442725893392, "lng"=> -90.51260768465767],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 39,
            //     "nombre" => "HOPELCHEN",
            //     "num_estacion" => '60028',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 23 (AV. PRINCIPAL), No. 21, COL. SAN ROMÁN, C.P. 24600',
            //     'coordenadas'=> ["lat"=>19.748424408962688, "lng"=> -89.85366448893052],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 40,
            //     "nombre" => "20 DE NOVIEMBRE",
            //     "num_estacion" => 60013.0,
            //    "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 41,
            //     "nombre" => "CANCÚN MADERO",
            //     "num_estacion" => 13344.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 42,
            //     "nombre" => "EL IDEAL",
            //     "num_estacion" => 6602.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 43,
            //     "nombre" => "LOPEZ PORTILLO",
            //     "num_estacion" => 60002.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 44,
            //     "nombre" => "LOPEZ PORTILLO 2",
            //     "num_estacion" => 60016.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 45,
            //     "nombre" => "RANCHO VIEJO",
            //     "num_estacion" => 60014.0,
            //    "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 46,
            //     "nombre" => "RUTA 5",
            //     "num_estacion" => 60015.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 47,
            //     "nombre" => "TULUM COBA",
            //     "num_estacion" => 60030.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 48,
            //     "nombre" => "TULUM CRUCERO",
            //     "num_estacion" => 6774.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 49,
            //     "nombre" => "TULUM ZAMNA",
            //     "num_estacion" => 9886.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 50,
            //     "nombre" => "ANDRÉS QUINTANA ROO",
            //     "num_estacion" => 11065.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 51,
            //     "nombre" => "BACALAR",
            //     "num_estacion" => 10667.0,
            //     "zona" => 'QUINTANA ROO',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 4, LOTE 1, MANZANA 25, SIN COLONIA, MUNICIPIO DE BACALAR, OTHÓN P. BLANCO, QUINTANA ROO, C.P. 77930',
            //     'coordenadas'=> ["lat"=>18.671470883216404, "lng"=> -88.39822066197132],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 52,
            //     "nombre" => "FELIPE CARRILLO PUERTO",
            //     "num_estacion" => 13435.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 53,
            //     "nombre" => "HEROES",
            //     "num_estacion" => 11072.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 54,
            //     "nombre" => "HUAY PIX",
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 55,
            //     "nombre" => "KOHUNLICH",
            //     "num_estacion" => 12454.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 56,
            //     "nombre" => "MAXUXAC",
            //     "num_estacion" => 11063.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 57,
            //     "nombre" => "MAXUXAC 2",
            //     "num_estacion" => 13559.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 58,
            //     "nombre" => "PEDRO SANTOS",
            //     "num_estacion" => 9816.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 59,
            //     "nombre" => "ROJO GÓMEZ",
            //     "num_estacion" => 11985.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 60,
            //     "nombre" => "PUEBLA CENTRO",
            //     "num_estacion" => 60021.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 61,
            //     "nombre" => "TORRECILLAS",
            //     "num_estacion" => 60023.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 62,
            //     "nombre" => "BOSQUES",
            //     "num_estacion" => 60026.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 63,
            //     "nombre" => "14 SUR",
            //     "num_estacion" => 60024.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 64,
            //     "nombre" => "HERMANOS SERDÁN",
            //     "num_estacion" => 60027.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 65,
            //     "nombre" => "AMALUCAN",
            //     "num_estacion" => 60025.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 66,
            //     "nombre" => "AGUA AZUL",
            //     "num_estacion" => 60031.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 67,
            //     "nombre" => "LOS ANGELES",
            //     "num_estacion" => 60032.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 68,
            //     "nombre" => "VILLA VERDE",
            //     "num_estacion" => 60034.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 69,
            //     "nombre" => "BOULEVARD NORTE",
            //     "num_estacion" => 60033.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 70,
            //     "nombre" => "HUAUCHINANGO",
            //     "num_estacion" => 5336.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 71,
            //     "nombre" => "TLAXCALA",
            //     "num_estacion" => 838.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 72,
            //     "nombre" => "SAN MATEO",
            //     "num_estacion" => 7181.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 73,
            //     "nombre" => "LA MARQUESA",
            //     "num_estacion" => 9620.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 74,
            //     "nombre" => "METEPEC",
            //     "num_estacion" => 4821.0,
            //    "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 75,
            //     "nombre" => "REAL VERONA",
            //     "num_estacion" => 60022.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 76,
            //     "nombre" => "ABROJALITO",
            //     "num_estacion" => 60010.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 77,
            //     "nombre" => "TECAMAC MP",
            //     "num_estacion" => 60003.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,"zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 78,
            //     "nombre" => "REAL GRANADA",
            //     "num_estacion" => 60008.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 79,
            //     "nombre" => "SIERRA HERMOSA",
            //     "num_estacion" => 13439.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 80,
            //     "nombre" => "CALIMAYA",
            //     "num_estacion" => 13530.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 81,
            //     "nombre" => "TUXTLA SANTA MARIA",
            //     "num_estacion" => '03493',
            //     "zona" => 'CHIAPAS',
            //     "status" => "Activo",
            //     "direccion" => 'BLVD. ÁNGEL ALBINO CORZO No. 914, LOS CHÓFERES, TUXTLA GUTIÉRREZ, CHIAPAS, C.P. 29078',
            //     'coordenadas'=> ["lat"=>16.748900010808647, "lng"=> -93.09112208465766],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            // ],
            // [
            //     "id" => 82,
            //     "nombre" => "TUXTLA BESLISARIO",
            //     "num_estacion" => '08755',
            //     "zona" => 'CHIAPAS',
            //     "status" => "Activo",
            //     "direccion" => 'CARRETERA INTERNACIONAL No. 6154, COL. PLAN DE AYALA. CHIAPAS, C.P. 29110',
            //     'coordenadas'=> ["lat"=>16.767455968170882, "lng"=> -93.1921522736257],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            // ],
            // [
            //     "id" => 83,
            //     "nombre" => "ARRIAGA",
            //     "num_estacion" => 334.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            // ],
            // [
            //     "id" => 84,
            //     "nombre" => "AGUASCALIENTES 1",
            //     "num_estacion" => '02468',
            //     "zona" => 'AGUASCALIENTES',
            //     "status" => "Activo",
            //     "direccion" => 'AV. ADOLFO LÓPEZ MATEOS OTE. No. 1502, HÉROES DE AGUASCALIENTES, AGUASCALIENTES, AGUASCALIENTES, C.P. 20250',
            //     'coordenadas'=> ["lat"=>21.877856032028575, "lng"=> -102.27079881349326],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // // [
            // //     "id" => 85,
            // //     "nombre" => "AGUASCALIENTES 1B",
            // //     "num_estacion" => 60018.0,
            // //     "zona" => 'YUCATÁN',
            // //     "status" => "Activo",
            // //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            // //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            // //     "combustibles" => [
            // //         "MAGNA" => true,
            // //         "PREMIUM" => true,
            // //         "DIESEL" => false,
            // //     ],
            // //     "is_new" => false,
            // // ],
            // // [
            // //     "id" => 86,
            // //     "nombre" => "AGUASCALIENTES 2",
            // //     "num_estacion" => 4437.0,
            // //     "zona" => 'YUCATÁN',
            // //     "status" => "Activo",
            // //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            // //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            // //     "combustibles" => [
            // //         "MAGNA" => true,
            // //         "PREMIUM" => true,
            // //         "DIESEL" => false,
            // //     ],
            // //     "is_new" => false,
            // // ],
            // [
            //     "id" => 87,
            //     "nombre" => "CELAYA 2",
            //     "num_estacion" => 5238.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 88,
            //     "nombre" => "LEÓN",
            //     "num_estacion" => 11617.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 89,
            //     "nombre" => "JUVENTINO",
            //     "num_estacion" => 13203.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 90,
            //     "nombre" => "SALAMANCA",
            //     "num_estacion" => 12802.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 91,
            //     "nombre" => "EL CAMPEÓN",
            //     "num_estacion" => 3680.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 92,
            //     "nombre" => "TEQUISQUIAPAN",
            //     "num_estacion" => 887.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 93,
            //     "nombre" => "EL PALOMAR",
            //     "num_estacion" => 9307.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 94,
            //     "nombre" => "LA BARCA",
            //     "num_estacion" => 5389.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 95,
            //     "nombre" => "ENSENADA 1",
            //     "num_estacion" => '12018',
            //     "zona" => 'BAJA CALIFORNIA',
            //     "status" => "Activo",
            //     "direccion" => 'CARRETERA TRANSPENINSULAR ENSENADA-SAN QUINTÍN KM.17+200, NACIONALISTA SÁNCHEZ TABOADA EJIDO, ENSENADA, C.P. 22790',
            //     'coordenadas'=> ["lat"=>31.76277900402114, "lng"=> -116.5875140150126],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 96,
            //     "nombre" => "ENSENADA 2",
            //     "num_estacion" => '60020',
            //     "zona" => 'BAJA CALIFORNIA',
            //     "status" => "Activo",
            //     "direccion" => 'AV. AMBROSIO DEL CASTILLO, No. 84, COL. EJIDO REAL DEL CASTILLO, ENSENADA, C.P. 22770',
            //     'coordenadas'=> ["lat"=>31.912401718920346, "lng"=> -116.27319270739633],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 97,
            //     "nombre" => "PREMIER",
            //     "num_estacion" => '10847',
            //     "zona" => 'BAJA CALIFORNIA',
            //     "status" => "Activo",
            //     "direccion" => 'CALZADA LIC. VICENTE LOMBARDO TOLEDANO No. 1839, CONJUNTO URBANO ESPERANZA, MEXICALI, BAJA CALIFORNIA, C.P. 21350',
            //     'coordenadas'=> ["lat"=>32.61604570153685, "lng"=> -115.47243541754113],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 98,
            //     "nombre" => "RIO NUEVO",
            //     "num_estacion" => '12508',
            //     "zona" => 'BAJA CALIFORNIA',
            //     "status" => "Activo",
            //     "direccion" => 'CALZADA DE LOS PRESIDENTES 401, RÍO NUEVO, MEXICALI, BAJA CALIFORNIA, C.P. 21120',
            //     'coordenadas'=> ["lat"=>32.65772097803069, "lng"=> -115.49169463253375],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 99,
            //     "nombre" => "TRAILERO",
            //     "num_estacion" => '10646',
            //    "zona" => 'BAJA CALIFORNIA',
            //     "status" => "Activo",
            //     "direccion" => 'CARRETERA MEXICALI A SAN FELIPE No. 568, RIVERA CAMPESTRE, MEXICALI, BAJA CALIFORNIA, C.P. 21386',
            //     'coordenadas'=> ["lat"=>32.58946450764353, "lng"=> -115.43087354350322],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 100,
            //     "nombre" => "OBREGÓN CENTRO",
            //     "num_estacion" => 5501.0,
            //    "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 101,
            //     "nombre" => "OBREGÓN MATRIZ",
            //     "num_estacion" => 8252.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 102,
            //     "nombre" => "OBREGÓN SUR",
            //     "num_estacion" => 9170.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [ 
            //     "id" => 103,
            //     "nombre" => "ALLENDE",
            //     "num_estacion" => '11415',
            //     "zona" => 'COAHUILA',
            //     "status" => "Activo",
            //     "direccion" => 'CARRETERA FEDERAL 57 KM 53 MARGEN IZQUIERDO N/A, ALLENDE, COAHUILA DE ZARAGOZA, C.P. 26530',
            //     'coordenadas'=> ["lat"=>28.31940398656287, "lng"=> -100.894575329387],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 104,
            //     "nombre" => "HERMANAS",
            //     "num_estacion" => 2210.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 105,
            //     "nombre" => "NUEVA ROSITA 2",
            //     "num_estacion" => 9865.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 106,
            //     "nombre" => "SABINAS",
            //     "num_estacion" => 9848.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 107,
            //     "nombre" => "COLÓN",
            //     "num_estacion" => 1984.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 108,
            //     "nombre" => "FELIX",
            //     "num_estacion" => 9773.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // // [
            // //     "id" => 109,
            // //     "nombre" => "CALKINI CENTRO",
            // //     "num_estacion" => '60035',
            // //     "zona" => 'CAMPECHE',
            // //     "status" => "Activo",
            // //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            // //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            // //     "combustibles" => [
            // //         "MAGNA" => true,
            // //         "PREMIUM" => true,
            // //         "DIESEL" => false,
            // //     ],
            // //     "is_new" => false,
            // // ],
            // [
            //     "id" => 110,
            //     "nombre" => "AMOZOC",
            //     "num_estacion" => 60037.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 111,
            //     "nombre" => "ATEXCAC",
            //     "num_estacion" => 60038.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 112,
            //     "nombre" => "ATLIXCO 1",
            //     "num_estacion" => 60042.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 113,
            //     "nombre" => "ATLIXCO 2",
            //     "num_estacion" => 60041.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 114,
            //     "nombre" => "CHOLULA",
            //     "num_estacion" => 60040.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 115,
            //     "nombre" => "FORJADORES",
            //     "num_estacion" => 60036.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 116,
            //     "nombre" => "PERINORTE",
            //     "num_estacion" => 60039.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 117,
            //     "nombre" => "RAMOS ARIZPE",
            //     "num_estacion" => 60043.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 118,
            //     "nombre" => "AMATITLAN",
            //     "num_estacion" => 50001.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 119,
            //     "nombre" => "CHIQUIMULILLA",
            //     "num_estacion" => 50006.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 120,
            //     "nombre" => "EL CAMAN",
            //     "num_estacion" => 50015.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 121,
            //     "nombre" => "EL RANCHO",
            //     "num_estacion" => 60014.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 122,
            //     "nombre" => "IZTAPA",
            //     "num_estacion" => 50019.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 123,
            //     "nombre" => "MAYA",
            //     "num_estacion" => 50011.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 124,
            //     "nombre" => "MAZATE",
            //     "num_estacion" => 50018.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 125,
            //     "nombre" => "PUENTE DE PALO",
            //     "num_estacion" => 50007.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 126,
            //     "nombre" => "SAN BARTOLO",
            //     "num_estacion" => 50008.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 127,
            //     "nombre" => "SAN BERNARDINO",
            //     "num_estacion" => 50020.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 128,
            //     "nombre" => "SAN MIGUEL",
            //     "num_estacion" => 50014.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 129,
            //     "nombre" => "SAN MIGUEL PETAPA",
            //     "num_estacion" => 50016.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 130,
            //     "nombre" => "SANTA ELENA",
            //     "num_estacion" => 50005.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 131,
            //     "nombre" => "SANTA MARIA",
            //     "num_estacion" => 50013.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 132,
            //     "nombre" => "SIBONEY 1",
            //     "num_estacion" => 50009.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 133,
            //     "nombre" => "SIBONEY 2",
            //     "num_estacion" => 50004.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 134,
            //     "nombre" => "TECULUTAN",
            //     "num_estacion" => 50012.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 135,
            //     "nombre" => "VALLADOLID MERCADO",
            //     "num_estacion" => 60044.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 37 NO. 180, COL. SANTA ANA, VALLADOLID, YUCATÁN, C.P 97782',
            //     'coordenadas'=> ["lat"=>20.691916828939895, "lng"=> -88.19465946777888],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 136,
            //     "nombre" => "TOLUCA",
            //     "num_estacion" => 60046.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 137,
            //     "nombre" => "JOSE MARIA MORELOS",
            //     "num_estacion" => 60047.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 138,
            //     "nombre" => "XONACA",
            //     "num_estacion" => 5236.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 139,
            //     "nombre" => "AMOZOC 2",
            //     "num_estacion" => 13306.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 140,
            //     "nombre" => "CAPU",
            //     "num_estacion" => 4772.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 141,
            //     "nombre" => "EL DORADO",
            //     "num_estacion" => 60048.0,
            //     "zona" => 'YUCATÁN',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 31 #836 Y 838 FRACC. CIUDAD CAUCEL C.P 97314',
            //     'coordenadas'=> ["lat"=>20.96268143064549, "lng"=> -89.61943298086513],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 142,
            //     "nombre" => "CALKINI CARRETERA",
            //     "num_estacion" => '60049',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'Carretera Federal Autopista Campeche – Mérida, Kilómetro 83 + 300, margen derecho. Localidad de Calkiní, Barrio Guadalupe, Calkiní, Campeche,C.P 24903',
            //     'coordenadas'=> ["lat"=>20.358727458185527, "lng"=> -90.04102464522173],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ],
            // [
            //     "id" => 143,
            //     "nombre" => "SEYBAPLAYA",
            //     "num_estacion" => '60050',
            //     "zona" => 'CAMPECHE',
            //     "status" => "Activo",
            //     "direccion" => 'CALLE 8 No. 1A Colonia GUADALUPE ciudad SEYBAPLAYA campeche cp: 24460',
            //     'coordenadas'=> ["lat"=>19.631794766479945, "lng"=> -90.68307253473579],
            //     "combustibles" => [
            //         "MAGNA" => true,
            //         "PREMIUM" => true,
            //         "DIESEL" => false,
            //     ],
            //     "is_new" => false,
            // ]
        ];

        return response()->json($estaciones);
    }
}
